export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";

export const CLEAR_ERROR_REQUEST = "CLEAR_ERROR_REQUEST";
export const CLEAR_ERROR_SUCCESS = "CLEAR_ERROR_SUCCESS";
export const CLEAR_ERROR_FAILURE = "CLEAR_ERROR_FAILURE";


export const POSTS_WRITE_REQUEST = "POSTS_WRITE_REQUEST";
export const POSTS_WRITE_SUCCESS = "POSTS_WRITE_SUCCESS";
export const POSTS_WRITE_FAILURE = "POSTS_WRITE_FAILURE";


export const POSTS_LOADING_REQUEST = "POSTS_LOADING_REQUEST";
export const POSTS_LOADING_SUCCESS = "POSTS_LOADING_SUCCESS";
export const POSTS_LOADING_FAILURE = "POSTS_LOADING_FAILURE";